
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MEVEN_DEPLOY_OPTS: "-DskipTests"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - testing
  - deploy

cache:
  key: "maven-cache-indexmic"
  paths:
    - .m2/repository
    - target/

build:
  image: maven:3.6-jdk-11-slim
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile

test-jar:
  image: maven:3.6-jdk-11-slim
  stage: testing
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test

deploy-wiki:
  image: tkikuchi/mkdocs-firebase-pipeline:node16-alpine
  stage: deploy
  only:
    - master
  script:
    - cd ./wiki
    - apk add git
    - git remote set-url origin https://$GIT_CI_USER:$GIT_CI_PASS@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git config --global user.email "comercial@proyais.com"
    - git config --global user.name "Gitlab Runner"
    - pip install mike
    - mike deploy --push $CI_COMMIT_BRANCH
