#!/bin/bash

if [ -d /etc/init ];
then
  cp -u /opt/indexmic/indexmic.conf /etc/init/indexmic.conf
fi

if [ -d /run/systemd/system ];
then
  cp -u /opt/indexmic/indexmic.service /etc/systemd/system/indexmic.service
  systemctl daemon-reload   
fi

# copy default configuration file
mkdir -p /etc/indexmic
if [ ! -e /etc/indexmic/application.yml ];
then
  cp /opt/indexmic/application-demo.yml /etc/indexmic/application.yml
  echo configuración de demostración creada en /etc/indexmic/application.yml
else
  echo utilizando configuración en /etc/indexmic/application.yml
fi

TEST=$(ps auxwww | grep /opt/indexmic | grep -c -v grep)
if [ $TEST -ne 0 ];
then
  echo indexmic ya está corriendo, reiniciando...
  service indexmic restart
  exit 0
else
  echo Iniciando indexmic...
  
  service indexmic start
  if [ -d /run/systemd/system ];
  then
    systemctl enable indexmic.service
  fi

  sleep 1
  TEST=$(ps auxwww | grep /opt/indexmic | grep -c -v grep)
  if [ $TEST -ne 0 ];
  then
    echo ¡IndexMic inicio con exito!
    exit 0
  else
    echo IndexMic no se pudo iniciar automaticamente, intenta  \`service indexmic start\`
    exit 1
  fi
fi
