#!/bin/bash

useradd -rMU indexmic || true

if [ -d /etc/indexmic ];
then
  if [ `stat -c '%U' /etc/indexmic/` != "indexmic" ];
  then
    chown -R indexmic:indexmic /etc/indexmic || true
  fi
fi

if [ -d /opt/indexmic ];
then
  if [ `stat -c '%U' /opt/indexmic/` != "indexmic" ];
  then
    chown -R indexmic:indexmic /opt/indexmic || true
  fi
fi
